In [ ]:
'''Q1. Create a Pandas Series that contains the following data: 4, 8, 15, 16, 23, and 42. Then, print the series.
'''
import pandas as pd

my_series=pd.Series([4, 8, 15, 16, 23,42])
print(my_series)

In [ ]:

'''Q2. Create a variable of list type containing 10 elements in it, and apply pandas.Series function on the
variable print it.'''

l=[range(1,11)]

my_series=pd.Series(l)
print(my_series)

In [ ]:
'''Q3. Create a Pandas DataFrame that contains the following data:

Name        Age         Gender

Alice       25          Female
Bob         30          male
Claire      27          Female


'''
import pandas as pd

data={'Name':['Alice','Bob','Claire'],
      'Age':[25,30,27],
      'Gender':['Female','Male','Female']
}

data_frame=pd.DataFrame(data)

print(data_frame)
print(type(data_frame))

In [ ]:
'''Q4. What is ‘DataFrame’ in pandas and how is it different from pandas.series? Explain with an example.
Ans-DataFrame is a two-dimensional labeled data structure in Pandas. It can be thought of as a table or spreadsheet consisting of rows and columns. Each column can have a different data type (such as float, int, string, etc.), and each row has a unique label or index. DataFrame is a versatile data structure that allows users to perform various operations on data, such as filtering, joining, merging, and reshaping.

On the other hand, Series is a one-dimensional labeled data structure in Pandas, which is similar to a column in a DataFrame. A Series can contain data of any data type (such as float, int, string, etc.) and has a unique label or index for each value in the series.

Here's an example to demonstrate the difference between DataFrame and Series. Suppose we have data on the heights and weights of three individuals:
'''
#DataFrame
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Height': [5.5, 6.0, 5.8],
    'Weight': [130, 150, 140]
}

df=pd.DataFrame(data)
print(df)

#Seires
height=df['Height']

print(height)
print(type(height))

In [ ]:
'''Q5. What are some common functions you can use to manipulate data in a Pandas DataFrame? Can
you give an example of when you might use one of these functions?


Ans-Pandas DataFrame provides a wide range of functions to manipulate data. Some of the common functions are:

head() and tail() - To view the first or last few rows of the DataFrame. These functions can be useful when we want to have a quick glance at the DataFrame.

info() and describe() - info() provides the summary of the DataFrame including the data types of each column and the number of non-null values. describe() provides the statistical summary of the numerical columns of the DataFrame.

sort_values() - To sort the rows of a DataFrame based on one or more columns. This function can be useful when we want to find the top or bottom values in a DataFrame based on a particular column.

groupby() and agg() - groupby() is used to group the rows of a DataFrame based on one or more columns. agg() is used to perform aggregations on the grouped data. These functions can be useful when we want to calculate summary statistics for different groups in the DataFrame.

drop() and fillna() - drop() is used to drop rows or columns from the DataFrame. fillna() is used to fill missing values in the DataFrame. These functions can be useful when we want to clean the DataFrame before analysis.

apply() - To apply a function to each element of a DataFrame. This function can be useful when we want to perform some custom operation on the DataFrame.

merge() - To merge two or more DataFrames based on one or more columns. This function can be useful when we want to combine data from multiple sources into a single DataFrame.

For example, we can use the groupby() function to group the data by a particular column, and then use the agg() function to calculate summary statistics for each group. For instance, we can group a DataFrame of sales data by the product category column, and then calculate the total revenue and average price for each category using the agg() function.


'''
import pandas as pd

# create a sample DataFrame
data = {'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emily'],
        'age': [25, 30, 25, 40, 45],
        'gender': ['F', 'M', 'M', 'M', 'F'],
        'salary': [50000, 60000, 70000, 80000,None]
        }


df=pd.DataFrame(data)

# view the first few rows of the DataFrame
print(df.head())

# view the last few rows of the DataFrame
print(df.tail())

# get the summary information of the DataFrame
print(df.info())

# get the statistical summary of the numerical columns of the DataFrame
print(df.describe())

# sort the DataFrame by age in descending order
df_sorted=df.sort_values('age',ascending=False)
print(df_sorted)

# group the DataFrame by gender and calculate the average salary for each group
grouped_df=df.groupby('gender').agg({'salary':'mean'})
print(grouped_df)

grouped_df=df.groupby('age').agg({'salary':'mean'})
print(grouped_df)

# drop the age column from the DataFrame
df_dropped=df.drop('age',axis=1)
print(df_dropped)

# fill missing values in the salary column with the mean salary
mean_salary = df['salary'].mean()
df_filled = df.fillna({'salary': mean_salary})
print(df_filled)

In [ ]:

'''Q6. Which of the following is mutable in nature Series, DataFrame, Panel?
Ans-In pandas, both Series and DataFrame are mutable in nature, while Panel is considered deprecated and its use is discouraged in favor of multi-dimensional arrays.

This means that you can modify the contents of a Series or DataFrame after it has been created. For example, you can add, delete, or update rows or columns in a DataFrame.

However, it's important to note that some operations in pandas, such as concatenation or merging, return new objects instead of modifying the original ones. Therefore, it's always a good practice to assign the result of an operation to a new variable if you want to keep the original object unchanged.
'''

In [ ]:
'''Q7. Create a DataFrame using multiple Series. Explain with an example.
'''

import pandas as pd

# create three Series containing data for three columns
column1 = pd.Series([1, 2, 3, 4])
column2 = pd.Series(['A', 'B', 'C', 'D'])
column3 = pd.Series([True, False, True, False])

# create the DataFrame by passing a dictionary with column names as keys and Series as values
df = pd.DataFrame({'Column 1': column1, 'Column 2': column2, 'Column 3': column3})

# print the DataFrame
print(df)